//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace openCaseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caseFramework
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public caseFramework()
        {
            this.Framework4Project = new HashSet<Framework4Project>();
            this.M_testCase = new HashSet<M_testCase>();
            this.M_testCaseSteps = new HashSet<M_testCaseSteps>();
        }
    
        public int ID { get; set; }
        public string workName { get; set; }
        public int userID { get; set; }
        public string controlXML { get; set; }
    
        public virtual admin_user admin_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Framework4Project> Framework4Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_testCase> M_testCase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_testCaseSteps> M_testCaseSteps { get; set; }
    }
}
