//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace openCaseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Framework4Project
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int FID { get; set; }
        public string controlXML { get; set; }
    
        public virtual caseFramework caseFramework { get; set; }
        public virtual project project { get; set; }
    }
}
