//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace openCaseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_runScene
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_runScene()
        {
            this.M_runTestCase = new HashSet<M_runTestCase>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string mark { get; set; }
        public Nullable<int> creatUser { get; set; }
        public Nullable<System.DateTime> creatDate { get; set; }
        public Nullable<int> deviceID { get; set; }
        public Nullable<int> DemandID { get; set; }
        public string installResult { get; set; }
    
        public virtual admin_user admin_user { get; set; }
        public virtual M_deviceConfig M_deviceConfig { get; set; }
        public virtual M_testDemand M_testDemand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_runTestCase> M_runTestCase { get; set; }
    }
}
