//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace openCaseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_testDemand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_testDemand()
        {
            this.M_runScene = new HashSet<M_runScene>();
            this.M_testDemand1 = new HashSet<M_testDemand>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string mark { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> baseID { get; set; }
        public Nullable<bool> isRun { get; set; }
        public Nullable<System.DateTime> runDate { get; set; }
        public Nullable<bool> visable { get; set; }
        public string apkName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_runScene> M_runScene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_testDemand> M_testDemand1 { get; set; }
        public virtual M_testDemand M_testDemand2 { get; set; }
        public virtual project project { get; set; }
    }
}
