//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace openCaseApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QCTESTEntities : DbContext
    {
        public QCTESTEntities()
            : base("name=QCTESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_log> admin_log { get; set; }
        public virtual DbSet<admin_user> admin_user { get; set; }
        public virtual DbSet<caseFramework> caseFramework { get; set; }
        public virtual DbSet<Framework4Project> Framework4Project { get; set; }
        public virtual DbSet<M_application> M_application { get; set; }
        public virtual DbSet<M_deviceConfig> M_deviceConfig { get; set; }
        public virtual DbSet<M_DevProMapping> M_DevProMapping { get; set; }
        public virtual DbSet<M_runScene> M_runScene { get; set; }
        public virtual DbSet<M_runTestCase> M_runTestCase { get; set; }
        public virtual DbSet<M_testCase> M_testCase { get; set; }
        public virtual DbSet<M_testCaseSteps> M_testCaseSteps { get; set; }
        public virtual DbSet<M_testDemand> M_testDemand { get; set; }
        public virtual DbSet<project> project { get; set; }
        public virtual DbSet<project_app> project_app { get; set; }
        public virtual DbSet<user_type> user_type { get; set; }
    }
}
