//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace openCaseApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QCTESTEntities : DbContext
    {
        public QCTESTEntities()
            : base("name=QCTESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_publicDevice> M_publicDevice { get; set; }
        public virtual DbSet<M_publicTask> M_publicTask { get; set; }
        public virtual DbSet<M_publicTaskResult> M_publicTaskResult { get; set; }
        public virtual DbSet<M_publicTaskScript> M_publicTaskScript { get; set; }
        public virtual DbSet<project> project { get; set; }
        public virtual DbSet<topic> topic { get; set; }
        public virtual DbSet<topicReply> topicReply { get; set; }
        public virtual DbSet<M_application> M_application { get; set; }
        public virtual DbSet<project_app> project_app { get; set; }
        public virtual DbSet<admin_user> admin_user { get; set; }
    }
}
