//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace openCaseMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_deviceConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_deviceConfig()
        {
            this.M_DevProMapping = new HashSet<M_DevProMapping>();
            this.M_runScene = new HashSet<M_runScene>();
        }
    
        public int ID { get; set; }
        public string IP { get; set; }
        public Nullable<int> Port { get; set; }
        public string device { get; set; }
        public string mark { get; set; }
        public string img { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_DevProMapping> M_DevProMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_runScene> M_runScene { get; set; }
    }
}
