//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace openCaseMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_runTestCase
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string testXML { get; set; }
        public Nullable<int> sceneID { get; set; }
        public string resultXML { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string resultPath { get; set; }
        public string mark { get; set; }
    
        public virtual M_runScene M_runScene { get; set; }
    }
}
