//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace openCaseMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int ID { get; set; }
        public int userID { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> topicID { get; set; }
        public Nullable<int> replyID { get; set; }
        public System.DateTime createDate { get; set; }
    
        public virtual admin_user admin_user { get; set; }
        public virtual topicReply topicReply { get; set; }
        public virtual topic topic { get; set; }
    }
}
